# Generated by Django 5.2.5 on 2025-08-26 00:57

import apps.evento2026.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento2026', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('organizacion', models.CharField(blank=True, max_length=200, null=True)),
                ('participaPeerReview', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2)),
                ('esEvaluador', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2)),
                ('cvFile', models.FileField(blank=True, null=True, upload_to=apps.evento2026.models.cv_upload_path)),
                ('nombres', models.CharField(blank=True, max_length=150, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=150, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='first_name',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='email',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='cv_file',
            new_name='cvFile',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='last_name',
            new_name='nombres',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='occupation',
            new_name='ocupacion',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='phone',
            new_name='telefono',
        ),
        migrations.AlterField(
            model_name='participant',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='evento2026.registration'),
        ),
        migrations.DeleteModel(
            name='GroupRegistration',
        ),
    ]
